CC      = icc
FC      = icc
CFLAGS  = -Wall -O3 -static-intel -qopenmp -parallel
LIBS    = -mkl -lpthread -static-intel -qopenmp -qopenmp-link=static

LDFLAGS = 
OBJS    = ilt.o nnls.o command.o output.o input.o BRDnewton_modify.o alpha_loop.o
PROGRAM = osilap

all: $(PROGRAM)

$(PROGRAM): $(OBJS)
	$(FC) $(OBJS) $(LDFLAGS) $(LIBS) -o $(PROGRAM)

clean:
	rm -f *.o *~ $(PROGRAM)

install: $(PROGRAM)
	install -s $(PROGRAM) $(DEST)
